# SW2PLA — Practice Exam 1
**Praktisk Lineær Algebra for Software Udviklere**

---

This exam contains **11 questions**. For each question:
- Write your code in the provided code cell(s)
- Make sure all results are **printed**
- Make sure all cell outputs are **visible** before exporting to PDF

> ⚠️ Questions marked **(GAI er ikke tilladt)** must be answered **in your own words** — do not use generative AI for these answers.

---


## Imports
Run this cell first.

In [5]:
import numpy as np
import scipy.linalg
import matplotlib.pyplot as plt


---
## Question 1 — Vectors

Given vectors **v** and **w** defined as:

$$v = \begin{bmatrix} 4 \\ 3 \end{bmatrix}, \quad w = \begin{bmatrix} 5 \\ 2 \end{bmatrix}$$

1. Calculate and print the **norm** of vector **v**.
2. Create and print a **unit vector** associated with **v**.
3. Compute and print the **dot product** of **v** and **w**.


In [6]:
# Question 1
v = np.array([4, 3])
w = np.array([5, 2])

# 1. Norm of v
# your code
norm_v=np.linalg.norm(v)
print("The norm of v is: ", norm_v)

# 2. Unit vector of v
# your code
unit_vector_v=(v/norm_v)
print("The unit vector is: ",'\n', unit_vector_v)

# 3. Dot product of v and w
# your code
dot_product_v_w = v @ w
print("The Dot product of v and w is: ", dot_product_v_w)


The norm of v is:  5.0
The unit vector is:  
 [0.8 0.6]
The Dot product of v and w is:  26


---
## Question 2 — Matrix Properties

Given the matrix:

$$A = \begin{bmatrix} 2 & 1 & 0 \\ 4 & 3 & 2 \\ 1 & 0 & 5 \end{bmatrix}$$

1. Construct and print matrix **A**.
2. Compute and print the **inverse** of **A**.
3. Compute and print the **determinant** of **A**.


In [7]:
# Question 2
# 1. Construct A
# your code
A = np.array([[2, 1, 0],
              [4, 3, 2],
              [1, 0, 5]])

print ("The matrix A:",'\n',A, '\n')

# 2. Inverse of A
# your code
#For at finde den inverse af A, bruger vi np.linalg.inv(x):
A_invers = np.linalg.inv(A)
print ("The inverse of A:",'\n', A_invers, '\n')


# 3. Determinant of A
# your code
#For at finde den determinanten af A, bruger vi np.linalg.det(x):
A_determinant = np.linalg.det(A)
print ("The determinant of A is: ",A_determinant)




The matrix A: 
 [[2 1 0]
 [4 3 2]
 [1 0 5]] 

The inverse of A: 
 [[ 1.25       -0.41666667  0.16666667]
 [-1.5         0.83333333 -0.33333333]
 [-0.25        0.08333333  0.16666667]] 

The determinant of A is:  11.999999999999995


---
## Question 3 — LU Decomposition

Using matrix **A** defined in Question 2:

1. Compute and print the **LU decomposition** of **A** (print matrices **P**, **L**, and **U**).
2. Verify the decomposition by reconstructing **A** from **P**, **L**, **U** and printing the result.


In [8]:
# Question 3
# 1. LU decomposition of A
# your code
# 1. LU decomposition of A
P, L, U = scipy.linalg.lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

# 2. Reconstruct A from P, L, U
#Her bruger vi vores matrix multiplikator "@"
A_reconstructed = P @ L @ U
print("Reconstructed A (verification):\n", A_reconstructed)




P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L:
 [[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [0.5        0.66666667 1.        ]]
U:
 [[ 4.    3.    2.  ]
 [ 0.   -0.75  4.5 ]
 [ 0.    0.   -4.  ]]
Reconstructed A (verification):
 [[2. 1. 0.]
 [4. 3. 2.]
 [1. 0. 5.]]


---
## Question 4 — System of Equations

Print the values of **x**, **y**, and **z** after computing the solution of the following system of equations:

$$\begin{cases} x + 2y + z = 8 \\ 3x + y - z = 6 \\ 2x + 3y + 2z = 14 \end{cases}$$


In [9]:
# Question 4
# your code
#Vi starter med at definerer vores arrays A og b, hvor A er ligningerne og b er resultaterne
EA = np.array([[1, 2, 1],
               [3, 1, -1],
               [2, 3, 2]])
Eb = np.array([8, 6, 14])

x = np.linalg.solve(EA,Eb)

#A er koefficienterne fra ligningerne, b er højresiderne, og solve finder x så Ax = b
print(f"x = {x[0]}, y = {x[1]}, z = {x[2]}")


x = 2.0000000000000004, y = 1.999999999999999, z = 2.000000000000001


---
## Question 5 — Eigendecomposition (Diagonalization)

Given matrix:

$$B = \begin{bmatrix} 5 & 2 & 0 \\ 2 & 3 & 0 \\ 0 & 0 & 4 \end{bmatrix}$$

1. **Diagonalize** matrix **B**. Print matrices **V**, **D**, and **V⁻¹**.
2. Use **V**, **D**, and **V⁻¹** to **reconstruct** matrix **B** and verify the result equals the original.


In [10]:
# Question 5
B = np.array([[5, 2, 0],
              [2, 3, 0],
              [0, 0, 4]], dtype=float)

# 1. Diagonalize B → eigenvalues (D) and eigenvectors (V)
# your code
eigenvalues, V = np.linalg.eig(B)
D = np.diag(eigenvalues)
V_inv = np.linalg.inv(V)

print ("V: \n", V)
print ("D: \n", D)
print ("V^-1 is the inverse. \n", "The inverse of V is: \n",V_inv)



# 2. Reconstruct B = V @ D @ V_inv and print
# your code
B_verify = V @ D @ V_inv
print ("To verify that V, D and V^-1 is the same as B, we multiply them with each other",
       "The output when we multiply the matrixes is: \n", B_verify, '\n',
       "Here is the original matrix B: \n", B)





V: 
 [[ 0.85065081 -0.52573111  0.        ]
 [ 0.52573111  0.85065081  0.        ]
 [ 0.          0.          1.        ]]
D: 
 [[6.23606798 0.         0.        ]
 [0.         1.76393202 0.        ]
 [0.         0.         4.        ]]
V^-1 is the inverse. 
 The inverse of V is: 
 [[ 0.85065081  0.52573111  0.        ]
 [-0.52573111  0.85065081  0.        ]
 [ 0.          0.          1.        ]]
To verify that V, D and V^-1 is the same as B, we multiply them with each other The output when we multiply the matrixes is: 
 [[5. 2. 0.]
 [2. 3. 0.]
 [0. 0. 4.]] 
 Here is the original matrix B: 
 [[5. 2. 0.]
 [2. 3. 0.]
 [0. 0. 4.]]


---
## Question 6 — Singular Value Decomposition (SVD)

Using matrix **B** from Question 5:

1. Compute the **SVD** of **B**. Print the resulting **U**, **S**, and **Vt** matrices.
2. Use **U**, **S**, **Vt** to **reconstruct** matrix **B** and verify the result equals the original.


In [ ]:
# Question 6
# 1. Compute SVD
# your code
U, S, Vt = np.linalg.svd(B)
print("U: \n", U)
print("S: \n", S)
print("Vt: \n", Vt)

# 2. Reconstruct B from U, S, Vt and verify
# your code

#First we convert S from a 1D array to a diagonal matrix:
S_matrix = np.diag(S)
#Now we reconstruct B:
B_verify2 = U @ S_matrix @ Vt
print ("B: \n", B , '\n')
print ("Verification (U @ S (matrix form) @ Vt) \n", B_verify2)



U: 
 [[-0.85065081  0.         -0.52573111]
 [-0.52573111  0.          0.85065081]
 [ 0.          1.          0.        ]]
U: 
 [6.23606798 4.         1.76393202]
U: 
 [[-0.85065081 -0.52573111 -0.        ]
 [ 0.          0.          1.        ]
 [-0.52573111  0.85065081  0.        ]]
B: 
 [[5. 2. 0.]
 [2. 3. 0.]
 [0. 0. 4.]] 

Verification (U @ S (matrix form) @ Vt) 
 [[5. 2. 0.]
 [2. 3. 0.]
 [0. 0. 4.]]


---
## Question 7 — Generalized Linear Model (GLM / Least Squares)

The following dataset shows the number of hours a student studied and the resulting exam score:

| Hours studied | Exam score |
|:---:|:---:|
| 3 | 55 |
| 5 | 70 |
| 6 | 75 |
| 8 | 88 |
| 9 | 90 |
| 4 | 62 |
| 7 | 82 |

1. Use the **least squares** function to solve the GLM and print the resulting equation (e.g. `y = β1*x + β0`).
2. Print the **predicted score** for a student who studied **6.5 hours**.
3. Print the **SSE** (Sum of Squared Errors).


In [12]:
# Question 7
hours  = np.array([3, 5, 6, 8, 9, 4, 7], dtype=float)
scores = np.array([55, 70, 75, 88, 90, 62, 82], dtype=float)

# 1. Build design matrix and solve using least squares
# your code
X = np.column_stack([hours, np.ones(len(hours))])  # Building the design matrix
result = np.linalg.lstsq(X, scores, rcond=None) #Solving using least squares
beta1, beta0 = result[0]
print(f"y = {beta1:.4f}*x + {beta0:.4f}")


# 2. Predicted score for 6.5 hours
# your code
predicted = beta1 * 6.5 + beta0
print(f"Predicted score for 6.5 hours: {predicted:.2f}")

# 3. SSE
# your code
scores_predicted = X @ result[0]
SSE = np.sum((scores - scores_predicted)**2)
print(f"SSE: {SSE:.4f}")

y = 6.0357*x + 38.3571
Predicted score for 6.5 hours: 77.59
SSE: 15.6786


---
## Question 8 — Orthogonal Matrices *(GAI er ikke tilladt)*

Given any orthogonal matrix **Q**, which of the following is a **correct** statement?

1. $Q^{-1} = -Q^T$
2. $Q^T Q = I$
3. None of the above.

**Answer and explain your reasoning in a markdown cell below.** You may support your answer with code.


### Answer to Question 8

*(Write your answer here in your own words)*


The second statement is correct. It is a standard orthogonal check. This statements makes sure that it is a orthogonal matrix - if it returns an identity matrix, the check is verified

In [13]:
# Question 8 — optional supporting code
# your code
#Code to support my statement:
angle = np.radians(45)
Q = np.array([[ np.cos(angle), -np.sin(angle)],
              [ np.sin(angle),  np.cos(angle)]])

print("Q (rotation 45°):")
print(np.round(Q, 4))

# Tjek Q^T Q = I
print("\nTjek Q.T @ Q = I:")
print(np.round(Q.T @ Q, 6))




Q (rotation 45°):
[[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]

Tjek Q.T @ Q = I:
[[ 1. -0.]
 [-0.  1.]]


---
## Question 9 — Linear Independence & Rank *(GAI er ikke tilladt)*

Given the matrix:

$$C = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$$

1. What is the **rank** of **C**? Print it using code.
2. Are the **columns** of **C** linearly independent? Answer using **theoretical reasoning** (not just code). *(Hint: use the result from 1.)*


### Answer to Question 9.2

*(Write your theoretical reasoning here in your own words)*


In [16]:
# Question 9 — Rank of C
C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)

# 1. Compute and print the rank of C
# your code

print ("1. Rank af matrix C = ", np.linalg.matrix_rank(C))
print ("2. No the columns of C is not linearly independent.\n" \
"The rank would be 3 in that case.\n",
"The columns of a matrix is only independent if, and only if, the rank of the matrix is equal to how many colums it has")


1. Rank af matrix C =  2
2. No the columns of C is not linearly independent.
The rank would be 3 in that case.
 The columns of a matrix is only independent if, and only if, the rank of the matrix is equal to how many colums it has


---
## Question 10 — SVD and Eigendecomposition *(GAI er ikke tilladt)*

Provide a short paragraph that explains the **relationship between eigendecomposition and SVD**.

- Under what conditions are they equivalent?
- How can the left singular vectors of a matrix **A** be derived from an eigendecomposition?


### Answer to Question 10

*(Write your answer here in your own words)*


- SVD and Eigendecomposition is equivalent when the matrix is square and symmetrical, since SVD is the general version of eigendecomposition, and can be used on all matrixes. The eigendecomposition can only be used on matrixes that is diagonalizable.
- The left singular vectors of a matrix A is U from the formula $A=U\sum V^T$.
Can be derived from an eigendecomposition, by making a eigendecomposition of $AA^T$, which is exactly U.
in python it looks like this:

In [19]:
evals, U = np.linalg.eigh(A @ A.T)

Basically, what it means to derive the left singular vectors of matrix A from an eigendecomposition, is to make a eigendecomposition of $AA^T$ 

---
## Question 11 — Low-Rank Approximation *(GAI er ikke tilladt)*

Given that we obtained an SVD decomposition of a matrix $A = U \Sigma V^T$ where the singular values are $s_1, s_2, \ldots, s_r$, with $s_1 \geq s_2 \geq \ldots \geq s_r > 0$.

1. Write the **mathematical expression** that shows the reconstruction of **A** as a sum of all rank-1 layers of the SVD.
2. Define in **your own words** what a **low-rank approximation** of **A** is, and why it is useful.


### Answer to Question 11

*(Write your answer here in your own words)*


The mathematical expression that shows the reconstruction af A as a sum of all rank-1 layes of the SVD is:
$$\sum_{i=1}^{r} \sigma_i \cdot U_i \cdot V_i^T$$


It is good for composition, so that we have a lot fewer numbers to deal with.
Low-Rank approximation sorts the rank-1 layers after the importance of the singular values. The biggest singular values contains the most information, so you can keep the important numbers, and throw away the noise.