# SW2PLA — Practice Exam 2
**Praktisk Lineær Algebra for Software Udviklere**

---

This exam contains **11 questions**. For each question:
- Write your code in the provided code cell(s)
- Make sure all results are **printed**
- Make sure all cell outputs are **visible** before exporting to PDF

> ⚠️ Questions marked **(GAI er ikke tilladt)** must be answered **in your own words** — do not use generative AI for these answers.

---


In [108]:
import numpy as np
import scipy.linalg
import matplotlib.pyplot as plt


---
## Question 1 — Vectors

Given vectors **v** and **w** defined as:

$$v = \begin{bmatrix} 6 \\ 8 \\ 0 \end{bmatrix}, \quad w = \begin{bmatrix} 3 \\ 4 \\ 0 \end{bmatrix}$$

1. Calculate and print the **norm** of **v** using both `np.linalg.norm` and **manually** (without a built-in function).
2. Create and print the **unit vector** of **v**.
3. Compute and print the **dot product** of **v** and **w**.
4. Are **v** and **w** orthogonal? Print a boolean answer.


In [109]:
# Question 1
v = np.array([6, 8, 0])
w = np.array([3, 4, 0])

# 1. Norm — numpy and manual
# your code
print ("Using np.linalg.norm: ", np.linalg.norm(v))
print ("Manually: ", np.sqrt(np.sum(v**2)))


# 2. Unit vector of v
# your code
print ("Unit vector of v: \n", (v/np.linalg.norm(v)))


# 3. Dot product
# your code
print ("The dot product of v and w: \n", np.dot(v, w))

# 4. Are v and w orthogonal?
# your code

print("v og w er ortogonale:", np.dot(v, w) == 0)



Using np.linalg.norm:  10.0
Manually:  10.0
Unit vector of v: 
 [0.6 0.8 0. ]
The dot product of v and w: 
 50
v og w er ortogonale: False


---
## Question 2 — Matrix Properties

Given the matrix:

$$A = \begin{bmatrix} 3 & 1 & 2 \\ 0 & 4 & 1 \\ 2 & 1 & 3 \end{bmatrix}$$

1. Construct and print matrix **A**.
2. Is **A** symmetric? Print a boolean answer and explain briefly why/why not.
3. Compute and print the **trace** of **A**.
4. Compute and print the **determinant** of **A**.
5. Is **A** invertible? Use the determinant to argue.


In [110]:
# Question 2
# 1. Construct A
# your code
A = np.array([[3, 1, 2],
              [0, 4, 1],
              [2, 1, 3]])

# 2. Is A symmetric?
# your code
print("\n Er A symmetrisk?", np.allclose(A, A.T), '\n')

# 3. Trace
# your code
print ("The trace og matrix A is: ",np.trace(A),'\n')

# 4. Determinant
# your code
print ("The determinant of A is: ", np.linalg.det(A),'\n')

# 5. Invertible?
# your code
print("The determant is invertibel since it is not 0.")
print ("Verification:")
print("Invertibel:", abs(np.linalg.det(A)) > 1e-10)


 Er A symmetrisk? False 

The trace og matrix A is:  10 

The determinant of A is:  19.000000000000004 

The determant is invertibel since it is not 0.
Verification:
Invertibel: True


---
## Question 3 — QR Decomposition

Using matrix **A** from Question 2:

1. Compute and print the **QR decomposition** of **A** (print **Q** and **R**).
2. Verify that **Q** is orthogonal by checking $Q^T Q = I$. Print the result.
3. Verify the decomposition by reconstructing **A** from **Q** and **R**.


In [ ]:
# Question 3
# 1. QR decomposition
# your code
Q, R = np.linalg.qr(A)
print ("Q: \n", np.round(Q,3), '\n', "R: \n", np.round(R), '\n')

# 2. Verify Q is orthogonal
# your code

print("\n Verification that Q is orthogonal: \n", np.round(Q.T @ Q, 6))
print ("\nI is the identity matrix, so yes Q is orthogonal")


# 3. Reconstruct A
# your code
print ("Verifying the decomposition: \n", Q @ R)
print ("A: \n", A)

Q: 
 [[-1.  0. -1.]
 [-0. -1. -0.]
 [-1. -0.  1.]] 
 R: 
 [[-4. -1. -3.]
 [ 0. -4. -1.]
 [ 0.  0.  1.]] 


 Verification that Q is orthogonal: 
 [[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]

I is the identity matrix, so yes Q is orthogonal
Verifying the decomposition: 
 [[3. 1. 2.]
 [0. 4. 1.]
 [2. 1. 3.]]
A: 
 [[3 1 2]
 [0 4 1]
 [2 1 3]]


---
## Question 4 — System of Equations

Print the values of **x**, **y**, and **z** after solving:

$$\begin{cases} 3x + y + 2z = 10 \\ 4y + z = 9 \\ 2x + y + 3z = 11 \end{cases}$$


In [112]:
# Question 4
# your code
Eq_A = np.array ([[3, 1, 2],
                 [0, 4, 1],
                 [2, 1, 3]])
Eq_b = ([10, 9, 11])

x = np.linalg.solve(Eq_A,Eq_b)
print ("x = ",x[0])
print ("y = ",x[1])
print ("z = ",x[2])



x =  1.2631578947368418
y =  1.6842105263157894
z =  2.2631578947368425


---
## Question 5 — Eigendecomposition (Diagonalization)

Given matrix:

$$B = \begin{bmatrix} 6 & 2 & 0 \\ 2 & 3 & 0 \\ 0 & 0 & 5 \end{bmatrix}$$

1. **Diagonalize** matrix **B**. Print **V**, **D**, and **V⁻¹**.
2. Reconstruct **B** from **V**, **D**, **V⁻¹** and verify the result.


In [113]:
# Question 5
B = np.array([[6, 2, 0],
              [2, 3, 0],
              [0, 0, 5]], dtype=float)

# 1. Diagonalize
# your code
eigenvalues, V = np.linalg.eig(B)
D   = np.diag(eigenvalues)
V_inv = np.linalg.inv(V)

print ("V: \n", np.round(V,4), "\nD: \n", np.round(D,4), "\nV^1: \n", np.round(V_inv,4), '\n')

# 2. Reconstruct and verify
# your code
B_rec = V @ D @ V_inv
print ("Reconstruction: \n", B_rec)
print ("The matrix B: \n", B)


V: 
 [[ 0.8944 -0.4472  0.    ]
 [ 0.4472  0.8944  0.    ]
 [ 0.      0.      1.    ]] 
D: 
 [[7. 0. 0.]
 [0. 2. 0.]
 [0. 0. 5.]] 
V^1: 
 [[ 0.8944  0.4472  0.    ]
 [-0.4472  0.8944  0.    ]
 [ 0.      0.      1.    ]] 

Reconstruction: 
 [[6. 2. 0.]
 [2. 3. 0.]
 [0. 0. 5.]]
The matrix B: 
 [[6. 2. 0.]
 [2. 3. 0.]
 [0. 0. 5.]]


---
## Question 6 — Singular Value Decomposition (SVD)

Using matrix **B** from Question 5:

1. Compute the **SVD** of **B**. Print **U**, **S**, and **Vt**.
2. Reconstruct **B** from **U**, **S**, **Vt** and verify.
3. Compute and print a **rank-2 low-rank approximation** of **B** and print the approximation error (Frobenius norm).


In [114]:
# Question 6
# 1. Compute SVD
# your code

U, S, Vt = np.linalg.svd(B)

print ("U: \n", np.round(U,4), "\nS: \n", np.round (S,4), "\n Vt: \n", np.round(Vt,4), '\n')


# 2. Reconstruct and verify
# your code
Sigma = np.zeros_like(B)
np.fill_diagonal(Sigma, S)
B_rec2 = U @ Sigma @ Vt
print("\nVerifikation U @ Sigma @ Vt ≈ B:"); print(np.round(B_rec2, 6))
print ("B: \n", B)

# 3. Rank-2 approximation + error
# your code
k = 2
B_approx = sum(S[i] * np.outer(U[:,i], Vt[i,:]) for i in range(k))
print(f"\nLow-rank approximation (k={k}):"); print(np.round(B_approx, 4))
print(f"Error (Frobenius): {np.linalg.norm(B - B_approx):.4f}", "\n")

print("The Frobenius norm is a size of a matrix. \n",
"It is used to measure the amount of information that is lost (in this case) \n",
"a rank-2 approximation. The lower the better",'\n'
"< 1% is very good \n1-5% is acceptable \n > 10% big information loss")
print ("Here it is in %:")
error_rel = np.linalg.norm(B - B_approx) / np.linalg.norm(B) * 100
print("Approksimationsfejl: ", error_rel, "%")



U: 
 [[-0.8944  0.     -0.4472]
 [-0.4472  0.      0.8944]
 [ 0.      1.      0.    ]] 
S: 
 [7. 5. 2.] 
 Vt: 
 [[-0.8944 -0.4472 -0.    ]
 [ 0.      0.      1.    ]
 [-0.4472  0.8944  0.    ]] 


Verifikation U @ Sigma @ Vt ≈ B:
[[6. 2. 0.]
 [2. 3. 0.]
 [0. 0. 5.]]
B: 
 [[6. 2. 0.]
 [2. 3. 0.]
 [0. 0. 5.]]

Low-rank approximation (k=2):
[[5.6 2.8 0. ]
 [2.8 1.4 0. ]
 [0.  0.  5. ]]
Error (Frobenius): 2.0000 

The Frobenius norm is a size of a matrix. 
 It is used to measure the amount of information that is lost (in this case) 
 a rank-2 approximation. The lower the better 
< 1% is very good 
1-5% is acceptable 
 > 10% big information loss
Here it is in %:
Approksimationsfejl:  22.645540682891912 %


---
## Question 7 — Generalized Linear Model (GLM / Least Squares)

A researcher measures outdoor temperature and ice cream sales:

| Temperature (°C) | Ice cream sales |
|:---:|:---:|
| 14 | 215 |
| 18 | 325 |
| 20 | 370 |
| 24 | 430 |
| 26 | 500 |
| 16 | 280 |
| 22 | 405 |
| 28 | 545 |

1. Use **least squares** to fit a linear model. Print the equation `y = β1*x + β0`.
2. Print the **predicted sales** when temperature is **25°C**.
3. Print the **SSE** and **R²**.


In [121]:
# Question 7
temp  = np.array([14, 18, 20, 24, 26, 16, 22, 28], dtype=float)
sales = np.array([215, 325, 370, 430, 500, 280, 405, 545], dtype=float)

# 1. Fit linear model
# your code
X = np.column_stack([temp, np.ones(len(temp))])
beta, _, _, _ = np.linalg.lstsq(X, sales, rcond=None)
beta1, beta0 = beta
print(f"Model: y = {beta1:.4f}x + {beta0:.4f}")


# 2. Predicted sales at 25°C
# your code
x_new = 25
y_pred = beta1 * x_new + beta0
print(f"Forudsagt score for {x_new} timer: {y_pred:.2f}")

# 3. SSE and R²
# your code
y_hat = X @ beta
SSE = np.sum((sales - y_hat)**2)
SS_tot = np.sum((sales - np.mean(sales))**2)
R2 = 1 - SSE / SS_tot
print(f"SSE: {SSE:.4f}")
print(f"R²:  {R2:.4f}  (1.0 = perfekt fit)")


Model: y = 22.3810x + -86.2500
Forudsagt score for 25 timer: 473.27
SSE: 835.1190
R²:  0.9902  (1.0 = perfekt fit)


---
## Question 8 — Rank & Nullspace *(GAI er ikke tilladt)*

Given the matrix:

$$M = \begin{bmatrix} 1 & 2 & 4 & 8 \\ 2 & 4 & 8 & 16 \\ 3 & 6 & 12 & 24 \end{bmatrix}$$

1. Compute and print the **rank** of **M**.
2. Compute and print the **dimension of the nullspace** of **M** using the rank-nullity theorem.
3. Does the vector $v = [2, -1, 0, 0]^T$ belong to the nullspace of **M**? Print a boolean answer.
4. In your own words: what does it mean that the nullspace has dimension > 0?


### Answer to Question 8.4

*(Write your answer here in your own words)*


In [122]:
# Question 8
M = np.array([[1,  2,  4,  8],
              [2,  4,  8, 16],
              [3,  6, 12, 24]], dtype=float)

# 1. Rank
# your code
rank = np.linalg.matrix_rank(M)
print ("Rank: ", rank)


# 2. Dim(nullspace)
# your code
nullity = M.shape[1] - rank
print ("Dimension of nullspace: ", nullity)

# 3. Does v = [2, -1, 0, 0] belong to nullspace?
v = np.array([2, -1, 0, 0], dtype=float)
# your code
Mv = M @ v
print("\nAv =", np.round(Mv, 10))
print("v tilhører nullspace:", np.allclose(Mv, 0))


Rank:  1
Dimension of nullspace:  3

Av = [0. 0. 0.]
v tilhører nullspace: True


Nullrummet indeholder alle vektorer vv
v hvor Av=0Av = 0
Av=0. Hvis dimensionen er større end 0, betyder det at der eksisterer vektorer der ikke er nulvektoren, som matricen sender til nul. Det betyder også at søjlerne ikke er lineært uafhængige — nogle søjler kan udtrykkes som lineære kombinationer af andre. Rang-nullitets-sætningen siger at jo større nullrummet er, jo færre lineært uafhængige søjler har matricen.

---
## Question 9 — Basis Transformation *(GAI er ikke tilladt)*

In $\mathbb{R}^3$, consider two bases:

$$B = \begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 1 & 0 \end{bmatrix}, \quad
F = \begin{bmatrix} 2 & 1 & 0 \\ 1 & 2 & 1 \\ 0 & 1 & 2 \end{bmatrix}$$

A vector $v$ has coordinates $(3, 1, 2)$ in basis **B**.

1. Find the coordinates of $v$ in the **standard basis**.
2. Find the coordinates of $v$ in basis **F**.
3. Verify your answer.

In your own words: what does it mean to change basis?


### Answer to Question 9.4

*(Write your answer here in your own words)*


In [123]:
# Question 9
B = np.array([[1, 0, 1],
              [0, 1, 1],
              [1, 1, 0]], dtype=float)

F = np.array([[2, 1, 0],
              [1, 2, 1],
              [0, 1, 2]], dtype=float)

c_B = np.array([3, 1, 2], dtype=float)

# 1. Coordinates in standard basis
# your code
v_std = B @ c_B
print("Koordinater i standardbasis:", v_std)


# 2. Coordinates in basis F
# your code
c_F = np.linalg.solve(F, v_std)
print("Koordinater i basis F:", np.round(c_F, 6))

# 3. Verification
# your code
print("Verifikation F @ c_F:", np.round(F @ c_F, 6))



Koordinater i standardbasis: [5. 3. 4.]
Koordinater i basis F: [ 3.25 -1.5   2.75]
Verifikation F @ c_F: [5. 3. 4.]


At skifte basis betyder at man beskriver den samme vektor med et nyt koordinatsystem. Vektoren selv ændrer sig ikke — kun de tal vi bruger til at beskrive den. Det svarer til at måle den samme afstand i km i stedet for miles: det er stadig den samme afstand, men tallene er anderledes.

---
## Question 10 — LU Decomposition *(GAI er ikke tilladt)*

1. Compute the **LU decomposition** of matrix **A** from Question 2. Print **P**, **L**, **U**.
2. Verify: $P \cdot L \cdot U = A$.
3. Compute $P \cdot P^T$. What type of matrix is **P**, and what does that tell you?


### Answer to Question 10.3

*(Write your answer here in your own words)*


In [128]:
# Question 10
A = np.array([[3, 1, 2],
              [0, 4, 1],
              [2, 1, 3]], dtype=float)

# 1. LU decomposition
# your code
P, L, U = scipy.linalg.lu(A)
print ("P: \n", P,  "\nL:\n", L, "\nU:\n", U)

# 2. Verify P @ L @ U = A
# your code
print ("A:\n", A)
print ("P @ L @ U: \n", P @ L @ U, '\n')

# 3. Compute P @ P.T and describe
# your code
print ("P @ P.T:\n", (P @ P.T))
print ("Since P @ P.T = I is a verification that it is orthogonal, and we get the identity matrix, its orthogonal")

P: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
L:
 [[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.66666667 0.08333333 1.        ]] 
U:
 [[3.         1.         2.        ]
 [0.         4.         1.        ]
 [0.         0.         1.58333333]]
A:
 [[3. 1. 2.]
 [0. 4. 1.]
 [2. 1. 3.]]
P @ L @ U: 
 [[3. 1. 2.]
 [0. 4. 1.]
 [2. 1. 3.]] 

P @ P.T:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Since P @ P.T = I is a verification that it is orthogonal, and we get the identity matrix, its orthogonal


---
## Question 11 — PCA *(GAI er ikke tilladt)*

Below is a small dataset with 3 features:

```python
X = np.array([[2.5, 2.4, 3.1],
              [0.5, 0.7, 1.2],
              [2.2, 2.9, 2.8],
              [1.9, 2.2, 2.5],
              [3.1, 3.0, 3.6],
              [2.3, 2.7, 2.9],
              [2.0, 1.6, 2.3],
              [1.0, 1.1, 1.5],
              [1.5, 1.6, 1.8],
              [1.1, 0.9, 1.3]], dtype=float)
```

Implement PCA using the **5 steps**:
1. Mean-center the data
2. Compute the covariance matrix
3. Compute eigendecomposition
4. Sort by descending eigenvalues
5. Project data onto the first **2** principal components

Then print:
- The **explained variance** per component (%)
- The **shape** of the projected data

In your own words: what do the principal components represent?


### Answer — what do principal components represent?

*(Write your answer here in your own words)*


In [134]:
# Question 11
X = np.array([[2.5, 2.4, 3.1],
              [0.5, 0.7, 1.2],
              [2.2, 2.9, 2.8],
              [1.9, 2.2, 2.5],
              [3.1, 3.0, 3.6],
              [2.3, 2.7, 2.9],
              [2.0, 1.6, 2.3],
              [1.0, 1.1, 1.5],
              [1.5, 1.6, 1.8],
              [1.1, 0.9, 1.3]], dtype=float)

# Step 1: Mean-center
# your code
X_centered = X - np.mean(X, axis=0, keepdims=True)

# Step 2: Covariance matrix
# your code
C = X_centered.T @ X_centered / (X_centered.shape[0] - 1)



# Step 3: Eigendecomposition
# your code
evals, evecs = np.linalg.eigh(C)



# Step 4: Sort descending
# your code
idx   = np.argsort(evals)[::-1]
evals = evals[idx]
evecs = evecs[:, idx]

# Step 5: Project onto 2 components
# your code
components = X @ evecs[:, :2]

# Print explained variance and shape
# your code
var_exp = evals / np.sum(evals) * 100
print ("Explained varians:")
for i, v in enumerate(var_exp):
    print(f"PC{i+1}: {v:.1f}%")

print("Shape of project onto 2 components:", components.shape)


Explained varians:
PC1: 96.9%
PC2: 2.6%
PC3: 0.5%
Shape of project onto 2 components: (10, 2)
