# Lesson 03 Exercise 1
You need to import numpy

## Exercise 1
Define the following vectors of $\mathbb{R}^3$

\begin{align*}
\mathbf{u}=(1,5,7)\\
\mathbf{v}=(2,5,9)
\end{align*}

#### Task 1
Calculate the three standard lengths of the vectors in numpy

That is $\lVert \cdot \rVert_{\infty}$,  $\lVert \cdot \rVert_{1}$ and  $\lVert \cdot \rVerts_{2}$


#### Task 2
Calculate the distance between $\mathbf{u}$ and $\mathbf{v}$ in the metrics induced by the three norms in numpy

#### Task 3
Verify that the triangle inequality $\lVert \mathbf{u}+\mathbf{v}\rVert \leq \lVert \mathbf{u}\rVert + \lVert \mathbf{v}\rVert$
in all three norms

Task 1:

In [11]:
#Task 1
import numpy as np

# Antag du har vektorerne
v_infty = np.array([1,2])  # Din vektor
v_1 = np.array([3,1])      # Din vektor
v_2 = np.array([5,2])      # Din vektor

# Beregn standard længder (L2 norm)
length_infty = np.linalg.norm(v_infty)
length_1 = np.linalg.norm(v_1)
length_2 = np.linalg.norm(v_2)

#length_infty = np.sqrt(np.sum(v_infty**2))
#length_1 = np.sqrt(np.sum(v_1**2))
#length_2 = np.sqrt(np.sum(v_2**2))

print(f"Length of v_∞: {length_infty}")
print(f"Length of v_1: {length_1}")
print(f"Length of v_2: {length_2}")


#Task 2

dist = np.sqrt(np.sum((v_1 - v_2)**2))

print(f"Distance between v_1 and v_2: {dist}")

#Task 3
sum = v_1 + v_2


# Verificer trekant-ulighed i L∞-norm
norm_inf_sum = np.linalg.norm(sum)
norm_inf_v_1 = np.linalg.norm(v_1)
norm_inf_v_2 = np.linalg.norm(v_2)

print("L∞-norm (Infinity norm):")
print(f"  ||u+v||∞ = {norm_inf_sum:.4f}")
print(f"  ||u||∞ + ||v||∞ = {norm_inf_v_1 + norm_inf_v_2:.4f}")
print(f"  Triangle inequality holds: {norm_inf_sum <= norm_inf_v_1 + norm_inf_v_2}")
print()

# Verificer trekant-ulighed i L2-norm
norm_2_sum = np.linalg.norm(sum, ord=2)
norm_2_v_1 = np.linalg.norm(v_1, ord=2)
norm_2_v_2 = np.linalg.norm(v_2, ord=2)

print("L2-norm (Euclidean norm):")
print(f"  ||u+v||₂ = {norm_2_sum:.4f}")
print(f"  ||u||₂ + ||v||₂ = {norm_2_v_1 + norm_2_v_2:.4f}")
print(f"  Triangle inequality holds: {norm_2_sum <= norm_2_v_1 + norm_2_v_2}")



Length of v_∞: 2.23606797749979
Length of v_1: 3.1622776601683795
Length of v_2: 5.385164807134504
Distance between v_1 and v_2: 2.23606797749979
L∞-norm (Infinity norm):
  ||u+v||∞ = 8.5440
  ||u||∞ + ||v||∞ = 8.5474
  Triangle inequality holds: True

L2-norm (Euclidean norm):
  ||u+v||₂ = 8.5440
  ||u||₂ + ||v||₂ = 8.5474
  Triangle inequality holds: True



## Exercise 2
Calculate the inner product of the two vectors from Exercise 1 in numpy

### Task 1
Calculate the inner product norm of the two vectors from exercise 1. This should be the same as $\lVert \cdot \rVert_2$-norm

### Task 2
Verify that Cauchy-Schwarz equation holds for the two vectors from Exercise 1



In [17]:
import numpy as np

v_infty = np.array([1,2])  # Din vektor
v_1 = np.array([3,1])      # Din vektor
v_2 = np.array([5,2])      # Din vektor

#Task 1
#Beregning af det indre produkt:
dot_v_1 = np.dot(v_1, v_infty)
dot_v_2 = np.dot(v_2, v_infty)
print(f"Indre produkt v_1:", dot_v_1)
print(f"Indre produkt v_2:", dot_v_2)


#Task 2
#Beregning af indre produkt normer
norm_v_1 = np.linalg.norm(v_1)
print(f"Normen af v_1: ", norm_v_1)
norm_v_2 = np.linalg.norm(v_2)
print(f"Normen af v_2: ", norm_v_2)
norm_sum = norm_v_1 + norm_v_2


#Task 3

print(f"  Cauchy-Schwarz equation holds: {norm_sum <= norm_v_1 + norm_v_2}")


Indre produkt v_1: 5
Indre produkt v_2: 9
Normen af v_1:  3.1622776601683795
Normen af v_2:  5.385164807134504
  Cauchy-Schwarz equation holds: True




## Exercise 3
Consider the basis
\begin{align*}
\mathbf{d}_1&=(1,1,0)\\
\mathbf{d}_2&=(1,-1,0)\\
\mathbf{d}_3&=(0,0,1)
\end{align*}

#### Task 1
Verify that this is an orthogonal basis

#### Task 2
Construct an orthonormal basis $\mathbf{f}_1,\mathbf{f}_2,\mathbf{f}_3$ from the $\mathbf{b}_i$ basis

#### Task 3
Express the vectors from Exercise 1 in basis $\mathbf{f}_i$

#### Task 4
Verify that the inner product in the coordinates of basis $\mathbf{f}_i$ is the same as the original inner product


In [28]:
import numpy as np

d_1 = np.array([1,1,0])
d_2 = np.array([1,-1,0])
d_3 = np.array([0,0,1])
a = 0
#Task 1
#Verificering af hvor vidt det er en orthogonal basis:
indre_produkter = d_1 * d_2 * d_3
print(f"Samlet indre produkt af d_1, d_2 & d_3:", indre_produkter)
print(f"  Cauchy-Schwarz equation holds: {indre_produkter <= 0}")

#Task 2
#Lav en orthogonal basis:
f_1 = np.array([-1,1,0])
f_2 = np.array([1,0,1])
f_3 = np.array([0,-1,1])

sum_indre_produkter = f_1 * f_2 * f_3
print(f"Indre produkt:", sum_indre_produkter)

#Task 3
F = np.column_stack([f_1, f_2, f_3])   # 3x3

# v = ...  # en af dine vektorer fra Exercise 1
c1 = np.linalg.solve(F, f_1)
c2 = np.linalg.solve(F, f_2)
c3 = np.linalg.solve(F, f_3)

print(c1)
print(c2)
print(c3)


Samlet indre produkt af d_1, d_2 & d_3: [0 0 0]
  Cauchy-Schwarz equation holds: [ True  True  True]
Indre produkt: [0 0 0]
[1. 0. 0.]
[-0.  1.  0.]
[-0.  0.  1.]


## Exercise 4

#### Task 1
Construct the projection $\mathbf{u}_{\parallel}$ of vector $\mathbf{u}$ onto $\mathbf{v}$

#### Task 2
Construct the orthogonal vectotor $\mathbf{u}_{\perp}$ of vector $\mathbf{u}_{\parallel}$

And verify the orthogonality



## Exercise 5
Calculate the angle between the vectors from exercise 1

