# Eksamen PLA

In [35]:
import numpy as np
import scipy.linalg
import matplotlib.pyplot as plt
from sympy import Matrix
import sympy as sym

## Question 1

Given vectors v and w defined as:
v = [3, -6, 2] and w = [0, 4, -1]
1. Calculate and print the norm of vector v.
2. Create and print a unit vector associated with v.
3. Compute and print the projection of v onto w

In [36]:
v = np.array([3, -6, 2])
w = np.array ([0, 4, -1])

#1 Norm of v
v_norm = np.linalg.norm(v)
print ("Norm af v: ", v_norm)

#2 unit vector of v
v_unit = v / v_norm
print("Enhedsvektor:", v_unit)
print("Verifikation — norm skal være 1:", np.round(np.linalg.norm(v_unit),2))

#3 projection of v onto w
#3 projection of v onto w
proj = (np.dot(v, w) / np.dot(w, w)) * w
print("Projektion af v onto w:", proj)



Norm af v:  7.0
Enhedsvektor: [ 0.42857143 -0.85714286  0.28571429]
Verifikation — norm skal være 1: 1.0
Projektion af v onto w: [-0.         -6.11764706  1.52941176]


## Question 2

Given a matrix defined as:
A =
[[2, 1, 0, 3],
[0, 4, 1, 2],
[1, 0, 3, 1],
[3, 2, 1, 0],
[1, 1, 2, 4]]
1. Create and print the matrix A.
2. Compute and print the trace and the Frobenius norm of A^T A.
3. How many linearly independent columns does A have? Justify your answer based on the
shape of A and your result from 2.2

In [37]:
#1 create and print matrix A
A = np.array([[2,1,0,3],
              [0,4,1,2],
              [1,0,3,1],
              [3,2,1,0],
              [1,1,2,4]])

print ("A: \n", A)

#2 Compute and print the trace and the Frobenius norm:
ATA = A.T @ A
print("A^T A:\n", ATA)
print("Trace of A^T A:", np.trace(ATA))
print("Frobenius norm of A^T A:", np.linalg.norm(ATA, 'fro'))

#3. How many linerly independent columns does A have:
rank = np.linalg.matrix_rank(A)
num_cols = A.shape[1]  # 4
print(f"Rank: {rank}, Number of columns: {num_cols}")
print(f"A has {rank} linearly independent columns.")
print(f"All columns independent: {rank == num_cols}")

A: 
 [[2 1 0 3]
 [0 4 1 2]
 [1 0 3 1]
 [3 2 1 0]
 [1 1 2 4]]
A^T A:
 [[15  9  8 11]
 [ 9 22  8 15]
 [ 8  8 15 13]
 [11 15 13 30]]
Trace of A^T A: 82
Frobenius norm of A^T A: 57.28874234961002
Rank: 4, Number of columns: 4
A has 4 linearly independent columns.
All columns independent: True


Since the matrix A is a 5x4 matrix, it has for columns. Since rank = 4 is the same as n (number of columns), all columns are linearly independant.

## Question 3

1. Construct the left inverse R of matrix A defined in Question 2.
2. Confirm that the matrix R you computed is in fact a left inverse. If a left inverse does not
exist, explain why and construct the right inverse instead (and verify that it is indeed a
right inverse.)

In [38]:
#1 left inverse R
R = np.linalg.inv(A.T @ A) @ A.T
print ("Left inverse R: \n", R)

#2 Confirm that the matrix R is the left inverse
print("R @ A:\n", np.round(R @ A, 6))
print("Is left inverse:", np.allclose(R @ A, np.eye(4)))



Left inverse R: 
 [[ 0.1527913  -0.15197988 -0.00673483  0.24602402 -0.03691983]
 [-0.05241805  0.24066861 -0.06247971  0.07757222 -0.06540084]
 [-0.18313859  0.02815644  0.28635183  0.00941253  0.05168776]
 [ 0.1495456  -0.01014281 -0.05704317 -0.13307368  0.157173  ]]
R @ A:
 [[ 1. -0. -0. -0.]
 [-0.  1. -0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -0. -0.  1.]]
Is left inverse: True


A left inverse exists because A is a 5×4 matrix with full column rank (rank = 4 = number of columns), so $(A^T A)$ is invertible and $R = (A^T A)^{-1} A^T$ is a valid left inverse.
A right inverse does not exist because A has more rows than columns (5 > 4), meaning A cannot span all of ℝ^5. A right inverse only exists when A has full row rank.

## Question 4

Print the values of x, y, z, and w after computing the solution of the following system of
equations:

2x + y - z + w = 4

x - y + 2z + w = 1

3x + 2y + z - w = 10

x + y + z + w = 6

In [39]:
A1 = np.array([[2,1,-1,1],
               [1,-1,2,1],
               [3,2,1,-1],
               [1,1,1,1]])
b1 = np.array ([4,1,10,6])

x = np.linalg.solve(A1,b1)
print ("x = ",np.round(x[0],2))
print ("y = ",np.round(x[1],2))
print ("z = ",np.round(x[2],2))
print ("w = ",np.round(x[3],2))


x =  0.87
y =  3.22
z =  1.43
w =  0.48


## Question 5

1. Diagonalize the matrix B:

B =

[[3, 1, 0],

[0, 3, 0],

[0, 1, 5]]

Print a matrix V, D, and V^-1. If the matrix is not diagonalizable, explain why.

2. Use V, D, and V^-1 to reconstruct B and verify that the reconstruction equals B

In [40]:
B = np.array ([[3, 1, 0],
               [0, 3, 0],
               [0, 1, 5]])

eigenvalues, V = np.linalg.eig(B)
D   = np.diag(eigenvalues)
V_inv = np.linalg.inv(V)

print ("V: \n", np.round(V,4), "\nD: \n", np.round(D,4), "\nV^-1: \n", np.round(V_inv,4), '\n')

print ("Rank of V: ",np.linalg.matrix_rank(V))
print ("det of V: ",np.round(np.linalg.det(V),2))

# Check if V is invertible (required for diagonalization)
if np.linalg.matrix_rank(V) < B.shape[0]:
    print("B is NOT diagonalizable: eigenvector matrix V is singular.")
    print("Eigenvalue 3 has algebraic multiplicity 2 but geometric multiplicity 1.")
else:
    D = np.diag(eigenvalues)
    V_inv = np.linalg.inv(V)
    print("V:\n", np.round(V, 4))
    print("D:\n", np.round(D, 4))
    print("V_inv:\n", np.round(V_inv, 4))
    B_rec = V @ D @ V_inv
    print("Reconstruction matches B:", np.allclose(B_rec, B))




V: 
 [[ 0.  1. -1.]
 [ 0.  0.  0.]
 [ 1.  0. -0.]] 
D: 
 [[5. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]] 
V^-1: 
 [[0.00000000e+00 5.00000000e-01 1.00000000e+00]
 [1.00000000e+00 1.50119988e+15 0.00000000e+00]
 [0.00000000e+00 1.50119988e+15 0.00000000e+00]] 

Rank of V:  2
det of V:  0.0
B is NOT diagonalizable: eigenvector matrix V is singular.
Eigenvalue 3 has algebraic multiplicity 2 but geometric multiplicity 1.


Since the rank of V (2) is not equal to n (3), and the determant is 0, V is singular which means B isn't diagonizable.

## Question 6

1. Compute the SVD of matrix B from Question 5. Print the resulting U, S, and V^T
matrices.
2. Use U, S, and V^T to reconstruct the matrix B and verify the reconstruction equals B

In [41]:
#1. SVD
U, S, Vt = np.linalg.svd(B)

S_matrix = np.diag(S)
print ("U: \n", np.round(U,4), "\nS: \n", np.round (S_matrix,4), "\n Vt: \n", np.round(Vt,4), '\n')

# 2. Reconstruct and verify

B_verify = U @ S_matrix @ Vt
print ("B: \n", B , '\n')
print ("Verification (U @ S (matrix form) @ Vt) \n", np.round(B_verify,2), '\n')
print ("Equals B?: ", np.allclose(B,B_verify))


U: 
 [[ 0.0916  0.7839  0.6141]
 [ 0.182   0.5932 -0.7842]
 [ 0.979  -0.1836  0.0883]] 
S: 
 [[5.1625 0.     0.    ]
 [0.     3.4693 0.    ]
 [0.     0.     2.5125]] 
 Vt: 
 [[ 0.0532  0.3131  0.9482]
 [ 0.6778  0.686  -0.2646]
 [ 0.7333 -0.6568  0.1757]] 

B: 
 [[3 1 0]
 [0 3 0]
 [0 1 5]] 

Verification (U @ S (matrix form) @ Vt) 
 [[ 3.  1. -0.]
 [-0.  3.  0.]
 [ 0.  1.  5.]] 

Equals B?:  True


## Question 7

The table below contains an artificial dataset of student performance. We want to use a GLM to predict the final exam score given a student's weekly hours of self-study and their number of completed assignments.

| Hours of Self-Study / Week | Completed Assignments | Exam Score |
|:--------------------------:|:---------------------:|:----------:|
| 3  | 8  | 68 |
| 5  | 10 | 78 |
| 7  | 6  | 82 |
| 6  | 12 | 90 |
| 8  | 9  | 88 |
| 4  | 5  | 65 |
| 9  | 11 | 95 |
| 5  | 7  | 74 |

1. Use the least squares Python function to solve the GLM, and print the resulting equation/model (e.g.: $y = B_2x_2 + B_1x_1 + B_0$).
2. Print the predicted score for 6 hours of self-study per week and 8 completed assignments.
3. Print the SSE value.

In [42]:
hours  = np.array([3, 5, 7, 6, 8, 4, 9, 5], dtype=float)
week   = np.array([8,10, 6,12, 9, 5,11, 7], dtype=float)
score  = np.array([68,78,82,90,88,65,95,74], dtype=float)

# Design matrix: [x1, x2, 1]
X = np.column_stack([hours, week, np.ones(len(hours))])

beta, _, _, _ = np.linalg.lstsq(X, score, rcond=None)
print(f"Model: y = {beta[0]:.4f}·x1 + {beta[1]:.4f}·x2 + {beta[2]:.4f}")

# 2. Predict for x1=6, x2=8
x_new = np.array([6, 8, 1])
y_pred = x_new @ beta
print(f"Predicted score (x1=6, x2=8): {y_pred:.4f}")

# 3. SSE
y_hat = X @ beta
SSE = np.sum((score - y_hat)**2)
print(f"SSE: {SSE:.4f}")

Model: y = 3.7726·x1 + 1.9357·x2 + 41.3830
Predicted score (x1=6, x2=8): 79.5037
SSE: 21.9082


## Question 8

Given an orthogonal matrix Q of size n by n. Which of the following is always a correct
statement?
1. The columns of Q form a basis for R^n.
2. The determinant of Q is always 1.
3. Q^T = -Q.
4. The eigenvalues of Q are always real.
5. None of the above.

2. The determinant of Q is always 1

$Q^TQ = I$

If we take the determinant on both sides:

$$\det(Q^TQ) = \det(I) = 1$$

We use: $\det(AB) = \det(A)\det(B)$ and $\det(Q^T) = \det(Q)$

$$\det(Q^T)\det(Q) = \det(Q)^2 = 1$$

$$ \det(Q) = \pm 1 \implies |\det(Q)| = 1$$




## Question 9

Given vectors a, b, c in R^4, such that the set V = {a, b, c} is linearly independent. Which of the
following is always a correct statement?
1. The span of V is all of R^4.
2. No vector in V can be written as a linear combination of the others.
3. Adding any vector d in R^4 to the set will keep it linearly independent.
4. The vectors a, b, c must be mutually orthogonal.
5. None of the above.

The correct statement is: 2. No vector in V can be written as a linear combination of the others, since they are all linearly independent

## Question 10

The SVD of a matrix A produces singular values s1 >= s2 >= ... >= sr > 0. Explain in your own
words what each singular value geometrically represents, and what it tells you about the matrix
A when one or more singular values are very small compared to the largest one

The singular values geometrically represents non-negative numbers on the diagonal of the scale along each axis.

The singular values are expressed as:
$$\Sigma = \begin{bmatrix} s_1 & & \\ & s_2 & \\ & & \ddots \end{bmatrix}, \quad s_1 \geq s_2 \geq \cdots \geq 0$$


They are ordered from largest to smallest and measures the importance of each component.

If one or more singular values are very small compared to the largest one, bassically it says that the difference in importance is big.

A small singular value means small scaling, whilst a big singular value means a big scaling. If the singular value = 0 the direction collapses completely


## Question 11

Given a tall, thin matrix A with many more rows than columns. Explain in your own words what
the column space of A is, why it is a subspace of R^m, and what the geometric intuition is for
projecting a vector b onto that column space. How does this connect to solving the least squares
problem?

The column space of a tall matrix A simply the span of its columns, $\text{col}(A) = \{A\mathbf{x} \mid \mathbf{x} \in R^n\}$ subspace of $R^m$ for range.

$$\text{col}(A) = \text{span}(\mathbf{a}_1, \mathbf{a}_2, \ldots, \mathbf{a}_n)$$

The geometric intuition for projecting a vector b:

Vector b, is probably not in our subspace, therefore we find the closest point that does.
It is basically what solving the least squares problem does:
1. Define the design matrix 
2. Define the response vector, which is already defined as vector b
3. Estimate $\hat{\beta}$
$$\hat{\boldsymbol{\beta}} = (X^TX)^{-1}X^T\mathbf{y}$$
4. Evaluate the model:
$$\hat{\mathbf{y}} = X\hat{\boldsymbol{\beta}}, \qquad \mathbf{e} = \mathbf{y} - \hat{\mathbf{y}}$$







### Kildeliste:
GAI - Claude Sonnet 4.6