# SW2PLA — Practice Exam 3
**Praktisk Lineær Algebra for Software Udviklere**

---

This exam focuses on topics **not yet covered** in Practice Exam 1 & 2:
vector projection, transformation matrices, RREF analysis, covariance matrix,
multi-variable GLM, GED/LDA, characteristic polynomial, and inverse properties.

This exam contains **11 questions**. For each question:
- Write your code in the provided code cell(s)
- Make sure all results are **printed**
- Make sure all cell outputs are **visible** before exporting to PDF

> ⚠️ Questions marked **(GAI er ikke tilladt)** must be answered **in your own words**.

---


In [1]:
import numpy as np
import scipy.linalg
import matplotlib.pyplot as plt
from sympy import Matrix


---
## Question 1 — Vector Projection & Angle

Given vectors:

$$u = \begin{bmatrix} 4 \\ 2 \\ 4 \end{bmatrix}, \quad v = \begin{bmatrix} 1 \\ 0 \\ 2 \end{bmatrix}$$

1. Compute and print the **projection** $u_\parallel$ of $u$ onto $v$.
2. Compute and print the **orthogonal complement** $u_\perp = u - u_\parallel$.
3. Verify orthogonality: print the dot product $u_\perp \cdot v$ (should be 0).
4. Compute and print the **angle** between $u$ and $v$ in degrees.


In [7]:
# Question 1
u = np.array([4, 2, 4], dtype=float)
v = np.array([1, 0, 2], dtype=float)

# 1. Projection of u onto v
# your code
dot_product_u_v = np.dot(u, v)
u_parallel = (dot_product_u_v / np.dot(v, v)) * v
print("Projection of u_parallel = ", u_parallel)


# 2. Orthogonal complement
# your code
u_perp = u - u_parallel
print("Orthogonal complement, u_perp = ", u_perp)

# 3. Verify orthogonality
# your code
print("u_perp · v = ", np.round(np.dot(u_perp, v), 4), "(should be ~0)")


# 4. Angle in degrees
# your code
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
angle_rad = np.arccos(np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v)))
print("Angle: ", np.degrees(angle_rad), "°")

Projection of u_parallel =  [2.4 0.  4.8]
Orthogonal complement, u_perp =  [ 1.6  2.  -0.8]
u_perp · v =  0.0 (should be ~0)
Angle:  26.565051177077994 °


---
## Question 2 — Transformation Matrices

A triangle has vertices at the following points (in homogeneous coordinates):

```python
triangle = np.array([[0, 0, 1],
                     [2, 0, 1],
                     [1, 2, 1]], dtype=float)
```

1. Construct a **rotation matrix** (homogeneous, $3\times3$) that rotates **60°** counterclockwise. Print the matrix.
2. Apply the rotation to the triangle and print the transformed vertices.
3. Construct a **translation matrix** that moves all points by $(+3, +1)$. Print the matrix.
4. Apply the translation to the **original** triangle and print the translated vertices.
5. Combine: rotate first, then translate. Print the final vertices.


In [15]:
# Question 2
triangle = np.array([[0, 0, 1],
                     [2, 0, 1],
                     [1, 2, 1]], dtype=float)

# 1. Rotation matrix (60°)
# your code
theta = np.radians(60)
R = np.array([
    [np.cos(theta), -np.sin(theta), 0],
    [np.sin(theta),  np.cos(theta), 0],
    [0,              0,             1]
    ])
print("Rotation matrix (60°):\n", R)

# 2. Rotated triangle
# your code
rotated = triangle @ R
print ("Triangle rotated 60°: \n",rotated)

# 3. Translation matrix (+3, +1)
# your code
T = np.array([[1, 0, 0],
              [0, 1, 0],
              [3, 1, 1]])
print ("Translation matrix: \n", T)

# 4. Translated triangle (from original)
# your code
translated = triangle @ T
print ("Translated triangle: \n", translated)


# 5. Rotate then translate (combined)
# your code
print ("First rotated:\n",rotated, "\n Translated: \n", rotated @ T)


Rotation matrix (60°):
 [[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]
Triangle rotated 60°: 
 [[ 0.          0.          1.        ]
 [ 1.         -1.73205081  1.        ]
 [ 2.23205081  0.1339746   1.        ]]
Translation matrix: 
 [[1 0 0]
 [0 1 0]
 [3 1 1]]
Translated triangle: 
 [[3. 1. 1.]
 [5. 1. 1.]
 [4. 3. 1.]]
First rotated:
 [[ 0.          0.          1.        ]
 [ 1.         -1.73205081  1.        ]
 [ 2.23205081  0.1339746   1.        ]] 
 Translated: 
 [[ 3.          1.          1.        ]
 [ 4.         -0.73205081  1.        ]
 [ 5.23205081  1.1339746   1.        ]]


---
## Question 3 — RREF & Number of Solutions

Consider the following three systems of equations:

**System A:**
$$\begin{cases} x + 2y + 3z = 6 \\ 2x + 5y + 2z = 4 \\ x + 3y - z = -2 \end{cases}$$

**System B:**
$$\begin{cases} x + 2y = 3 \\ 2x + 4y = 6 \end{cases}$$

**System C:**
$$\begin{cases} x + y = 5 \\ 2x + 2y = 3 \end{cases}$$

For **each** system:
1. Compute and print the **RREF** of the augmented matrix $[A|b]$.
2. Print `rank(A)` and `rank([A|b])`.
3. State how many solutions the system has and **why** (use rank reasoning).


### Answer — Number of solutions reasoning

*(Write your answers here for each system)*


In [21]:
# Question 3 — System A
print ("System A")
A_sys = np.array([[1, 2, 3],
                  [2, 5, 2],
                  [1, 3, -1]], dtype=float)
b_sys = np.array([[6], [4], [-2]], dtype=float)

# RREF and rank analysis
# your code
Ab = np.column_stack([A_sys, b_sys])
rref, pivots = Matrix(Ab).rref()
print(f"\nRREF of [A|b]:")
print(rref)
rank_A  = np.linalg.matrix_rank(A_sys)
rank_Ab = np.linalg.matrix_rank(np.column_stack([A_sys, b_sys]))

print(f"Rank A:    {rank_A}")
print(f"Rank [A|b]: {rank_Ab}")

if rank_A == rank_Ab == A_sys.shape[1]:
    x = np.linalg.solve(A_sys, b_sys)
    print(f"Unique solution: {x}\n")
elif rank_A == rank_Ab:
    print("Infinitely many solutions, since the rank < n\n")
else:
    print("No solution\n")

#System B:
print ("System B \n")

A_sysB = np.array([[1,2],
                   [2, 4]])
b_sysB = np.array([[3], [6]])

Ab_B = np.column_stack([A_sysB, b_sysB])
rref, pivots = Matrix(Ab_B).rref()
print(f"\nRREF of [A|b]:")
print(rref)
rank_A_B  = np.linalg.matrix_rank(A_sysB)
rank_Ab_B = np.linalg.matrix_rank(np.column_stack([A_sysB, b_sysB]))

print(f"Rank A:    {rank_A_B}")
print(f"Rank [A|b]: {rank_Ab_B}")

if rank_A_B == rank_Ab_B == A_sysB.shape[1]:
    xB = np.linalg.solve(A_sysB, b_sysB)
    print(f"Unique solution: {xB}\n")
elif rank_A_B == rank_Ab_B:
    print("Infinitely many solutions, since the rank < n\n")
else:
    print("No solution\n")

#System C:
print ("System C")

A_sysC = np.array([[1, 1],
                   [2, 2]])
b_sysC = np.array ([[5], [3]])

Ab_C = np.column_stack([A_sysC, b_sysC])
rref, pivots = Matrix(Ab_C).rref()
print(f"\nRREF of [A|b]:")
print(rref)
rank_A_C  = np.linalg.matrix_rank(A_sysC)
rank_Ab_C = np.linalg.matrix_rank(np.column_stack([A_sysC, b_sysC]))

print(f"Rank A:    {rank_A_C}")
print(f"Rank [A|b]: {rank_Ab_C}")

if rank_A_C == rank_Ab_C == A_sysC.shape[1]:
    xC = np.linalg.solve(A_sysC, b_sysC)
    print(f"Unique solution: {xC} \n")
elif rank_A_C == rank_Ab_C:
    print("Infinitely many solutions, since the rank < n \n")
else:
    print("No solution \n")


System A

RREF of [A|b]:
Matrix([[1, 0, 11.0000000000000, 22.0000000000000], [0, 1, -4.00000000000000, -8.00000000000000], [0, 0, 0, 0]])
Rank A:    2
Rank [A|b]: 2
Infinitely many solutions, since the rank < n

System B 


RREF of [A|b]:
Matrix([[1, 2, 3], [0, 0, 0]])
Rank A:    1
Rank [A|b]: 1
Infinitely many solutions, since the rank < n

System C

RREF of [A|b]:
Matrix([[1, 1, 0], [0, 0, 1]])
Rank A:    1
Rank [A|b]: 2
No solution 



In [ ]:
# Question 3 — System B
A_B = np.array([[1, 2],
                [2, 4]], dtype=float)
b_B = np.array([[3], [6]], dtype=float)

# your code


In [ ]:
# Question 3 — System C
A_C = np.array([[1, 2],
                [2, 2]], dtype=float)
b_C = np.array([[5], [3]], dtype=float)

# your code


---
## Question 4 — Covariance Matrix & Pearson Correlation

The following dataset contains measurements of 3 features for 6 observations:

```python
X = np.array([[2.5, 3.1, 8.0],
              [1.0, 1.5, 3.5],
              [3.0, 3.8, 9.5],
              [2.0, 2.5, 6.0],
              [4.0, 4.5, 12.0],
              [1.5, 2.0, 4.5]], dtype=float)
```

1. **Mean-center** the data (subtract column means). Print the column means.
2. Compute and print the **covariance matrix** $C = \frac{X^T X}{n-1}$.
3. Verify that $C$ is **symmetric**.
4. Compute and print the **Pearson correlation coefficient** between feature 1 and feature 3 (manually using the formula, not `np.corrcoef`).


In [28]:
# Question 4
X = np.array([[2.5, 3.1, 8.0],
              [1.0, 1.5, 3.5],
              [3.0, 3.8, 9.5],
              [2.0, 2.5, 6.0],
              [4.0, 4.5, 12.0],
              [1.5, 2.0, 4.5]], dtype=float)

# 1. Mean-center
# your code
mean = X - np.mean(X, axis=0, keepdims=True)
print("Column means:", np.mean(X, axis=0))
print("Mean-centered data:\n", np.round(mean, 4))


# 2. Covariance matrix
# your code
n = mean.shape[0]
C = mean.T @ mean / (n - 1)
print(f"\nCovariance matrix C:")
print(np.round(C, 4))

# 3. Verify symmetric
# your code
if np.allclose(C, C.T):
    print("\nC er symmetrisk eftersom C = C.T\n")
else:
    print("\nC er ikke symmetrisk\n")

# 4. Pearson correlation (manual) between feature 0 and feature 2
# your code
corr = C[0,2] / np.sqrt(C[0,0] * C[2,2])
print(f"\nPearson correlation: {corr:.4f}")



Column means: [2.33333333 2.9        7.25      ]
Mean-centered data:
 [[ 0.1667  0.2     0.75  ]
 [-1.3333 -1.4    -3.75  ]
 [ 0.6667  0.9     2.25  ]
 [-0.3333 -0.4    -1.25  ]
 [ 1.6667  1.6     4.75  ]
 [-0.8333 -0.9    -2.75  ]]

Covariance matrix C:
[[ 1.1667  1.21    3.45  ]
 [ 1.21    1.268   3.6   ]
 [ 3.45    3.6    10.275 ]]

C er symmetrisk eftersom C = C.T


Pearson correlation: 0.9964


---
## Question 5 — Characteristic Polynomial & Eigendecomposition

Given matrix:

$$A = \begin{bmatrix} 3 & 1 \\ 1 & 3 \end{bmatrix}$$

1. The characteristic polynomial of a $2\times 2$ matrix is $\lambda^2 - \text{tr}(A)\lambda + \det(A) = 0$. Compute and print the **eigenvalues** using this formula and `np.roots`.
2. Verify your result using `np.linalg.eig`.
3. Verify that $\text{tr}(A) = \sum \lambda_i$ and $\det(A) = \prod \lambda_i$.
4. Diagonalize $A$ — print $V$, $D$, and $V^{-1}$, and verify reconstruction.


In [ ]:
# Question 5
A = np.array([[3, 1],
              [1, 3]], dtype=float)

# 1. Eigenvalues from characteristic polynomial
# your code


# 2. Verify with np.linalg.eig
# your code


# 3. Verify tr(A) = sum(λ) and det(A) = prod(λ)
# your code


# 4. Diagonalize and verify reconstruction
# your code


---
## Question 6 — Multi-Variable GLM

A dataset records three variables for 8 students: hours studied, hours slept, and exam score.

| Hours studied | Hours slept | Exam score |
|:---:|:---:|:---:|
| 5 | 7 | 72 |
| 8 | 6 | 85 |
| 3 | 8 | 60 |
| 9 | 7 | 91 |
| 6 | 5 | 70 |
| 7 | 8 | 83 |
| 4 | 6 | 65 |
| 10 | 7 | 95 |

Fit the model: $y = \beta_0 + \beta_1 \cdot \text{studied} + \beta_2 \cdot \text{slept}$

1. Build the **design matrix** $X$ (columns: studied, slept, ones). Print it.
2. Solve using **least squares**. Print the model equation.
3. Predict the score for a student who studied **7.5 hours** and slept **7 hours**.
4. Compute and print **SSE** and **R²**.


In [ ]:
# Question 6
studied = np.array([5, 8, 3, 9, 6, 7, 4, 10], dtype=float)
slept   = np.array([7, 6, 8, 7, 5, 8, 6,  7], dtype=float)
scores  = np.array([72, 85, 60, 91, 70, 83, 65, 95], dtype=float)

# 1. Design matrix
# your code


# 2. Solve least squares and print model equation
# your code


# 3. Predict for studied=7.5, slept=7
# your code


# 4. SSE and R²
# your code


---
## Question 7 — QR-Based Inverse & Inverse Properties

Given matrices:

$$A = \begin{bmatrix} 2 & 1 & 1 \\ 0 & 3 & 1 \\ 1 & 1 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 1 & 2 & 0 \\ 0 & 1 & 1 \\ 2 & 0 & 1 \end{bmatrix}$$

1. Compute $A^{-1}$ using **QR decomposition** (formula: $A^{-1} = R^{-1}Q^T$). Print the result.
2. Verify it matches `np.linalg.inv(A)`.
3. Compute $(AB)^{-1}$ and $B^{-1}A^{-1}$. Are they equal? Print a boolean.
4. Compute $A^{-1}B^{-1}$. Is it equal to $(AB)^{-1}$? Print a boolean and explain.


### Answer to Question 7.4

*(Explain in your own words why the order matters)*


In [ ]:
# Question 7
A = np.array([[2, 1, 1],
              [0, 3, 1],
              [1, 1, 4]], dtype=float)
B = np.array([[1, 2, 0],
              [0, 1, 1],
              [2, 0, 1]], dtype=float)

# 1. QR-based inverse of A
# your code


# 2. Verify matches np.linalg.inv(A)
# your code


# 3. (AB)⁻¹ vs B⁻¹A⁻¹
# your code


# 4. A⁻¹B⁻¹ — is it equal to (AB)⁻¹?
# your code


---
## Question 8 — LU Determinant & Left Inverse

**Part A — LU determinant:**

Using matrix $A$ from Question 7:

1. Compute the **LU decomposition**. Print P, L, U.
2. Compute $\det(A)$ using the formula $\det(P) \cdot \prod_i U_{ii}$ and verify it matches `np.linalg.det(A)`.

**Part B — Left inverse:**

Given tall matrix:

$$T = \begin{bmatrix} 1 & 0 \\ 2 & 1 \\ 3 & 2 \end{bmatrix}$$

3. Compute the **left inverse** $T^+ = (T^TT)^{-1}T^T$. Print the result.
4. Verify: $T^+ \cdot T = I$.


In [ ]:
# Question 8 — Part A
A = np.array([[2, 1, 1],
              [0, 3, 1],
              [1, 1, 4]], dtype=float)

# 1. LU decomposition
# your code


# 2. det(A) via LU
# your code


# Part B — Left inverse
T = np.array([[1, 0],
              [2, 1],
              [3, 2]], dtype=float)

# 3. Left inverse
# your code


# 4. Verify T_left_inv @ T = I
# your code


---
## Question 9 — GED / LDA

The following data represents two classes:

```python
class1 = np.array([[1.2, 0.8], [1.5, 1.1], [0.9, 0.7],
                   [1.3, 0.9], [1.1, 1.0], [1.4, 0.8]])
class2 = np.array([[3.5, 2.8], [3.8, 3.1], [3.2, 2.6],
                   [3.6, 2.9], [3.4, 3.0], [3.9, 2.8]])
```

1. Compute and print **covB** (between-class covariance).
2. Compute and print **covW** (within-class covariance).
3. Solve the **GED** using `scipy.linalg.eig(covB, covW)`. Print the eigenvalues.
4. Project both classes onto the **best discriminant axis** (first eigenvector). Print the projected values.


In [ ]:
# Question 9
class1 = np.array([[1.2, 0.8], [1.5, 1.1], [0.9, 0.7],
                   [1.3, 0.9], [1.1, 1.0], [1.4, 0.8]])
class2 = np.array([[3.5, 2.8], [3.8, 3.1], [3.2, 2.6],
                   [3.6, 2.9], [3.4, 3.0], [3.9, 2.8]])

# 1. covB
# your code


# 2. covW
# your code


# 3. GED
# your code


# 4. Project onto best axis
# your code


---
## Question 10 — Eigenvalue Properties *(GAI er ikke tilladt)*

Given matrix:

$$M = \begin{bmatrix} 4 & 2 \\ 1 & 3 \end{bmatrix}$$

1. Compute eigenvalues of $M$ and $M^{-1}$. Verify that $\lambda(M^{-1}) = 1/\lambda(M)$.
2. Verify that the **eigenvectors** of $M$ and $M^{-1}$ are the same.
3. Compute and print: rank$(M)$, rank$(M^T)$, rank$(M^TM)$, rank$(MM^T)$. Are they all equal?
4. In your own words: **why** does $A^{-1}$ have eigenvalues $1/\lambda$ with the same eigenvectors? Explain using the eigendecomposition of $A$.


### Answer to Question 10.4

*(Explain in your own words using the eigendecomposition A = VΛV⁻¹)*


In [ ]:
# Question 10
M = np.array([[4, 2],
              [1, 3]], dtype=float)

# 1. Eigenvalues of M and M⁻¹
# your code


# 2. Verify eigenvectors are the same
# your code


# 3. Rank invariance
# your code


---
## Question 11 — Theory *(GAI er ikke tilladt)*

**Part A — Cauchy-Schwarz:**

1. State the **Cauchy-Schwarz inequality** in your own words.
2. Why does it guarantee that the formula $\cos(\theta) = \frac{u \cdot v}{\|u\|\|v\|}$ always gives a valid angle (i.e. $\cos(\theta) \in [-1, 1]$)?
3. Verify the inequality holds for $u = [1, 5, 7]$ and $v = [2, 5, 9]$.

**Part B — Characteristic polynomial:**

4. For a $2\times 2$ matrix $A$, the characteristic polynomial is $\lambda^2 - \text{tr}(A)\lambda + \det(A) = 0$. Explain in your own words **what the trace and determinant tell you** about the eigenvalues.


### Answer to Question 11

*(Write all answers here in your own words)*


In [ ]:
# Question 11 — Part A (verify Cauchy-Schwarz numerically)
u = np.array([1, 5, 7], dtype=float)
v = np.array([2, 5, 9], dtype=float)

# Verify |u·v| ≤ ||u|| * ||v||
# your code
